CREATE OR REPLACE TABLE JOMUMA1.AJEDRECISTAS FOR SYSTEM NAME AJEDRECI (
  ID DECIMAL(5, 0) NOT NULL GENERATED ALWAYS AS IDENTITY,
  NOMBRE CHAR(50) CCSID 1145 NOT NULL WITH DEFAULT,
  APELLIDOS CHAR(50) CCSID 1145 NOT NULL WITH DEFAULT,
  FEDERACION CHAR(20) CCSID 1145 NOT NULL WITH DEFAULT,
  ELO DECIMAL(4, 0) NOT NULL WITH DEFAULT,

  CONSTRAINT JOMUMA1.AJEDRECIK1 PRIMARY KEY(ID)
) RCDFMT RAJEDRECI;

LABEL ON TABLE JOMUMA1.AJEDRECISTAS IS 'AJEDRECISTAS'; 

LABEL ON COLUMN JOMUMA1.AJEDRECISTAS ( 
  ID          IS 'ID',
  NOMBRE      IS 'NOMBRE DE USUARIO',
  APELLIDOS   IS 'APELLIDOS DE USUARIO',
  FEDERACION  IS 'FEDERACION',
  ELO         IS 'ELO'
);

LABEL ON COLUMN JOMUMA1.AJEDRECISTAS ( 
  ID          TEXT IS 'ID',
  NOMBRE      TEXT IS 'NOMBRE DE USUARIO',
  APELLIDOS   TEXT IS 'APELLIDOS DE USUARIO',
  FEDERACION  TEXT IS 'FEDERACION',
  ELO         TEXT IS 'ELO'
);


-- ESTO SOLO LA PRIMERA VEZ QUE SE HAGA EL DEPLOY
INSERT INTO JOMUMA1.AJEDRECI VALUES(DEFAULT, 'MAGNUS', 'CARLSEN', 'NORUEGA', 2880);
INSERT INTO JOMUMA1.AJEDRECI VALUES(DEFAULT, 'ANAND', 'VISWANATHAN', 'INDIA', 2810);
INSERT INTO JOMUMA1.AJEDRECI VALUES(DEFAULT, 'JOSE RAUL', 'CAPABLANCA', 'CUBA', 2720);
INSERT INTO JOMUMA1.AJEDRECI VALUES(DEFAULT, 'BOBY', 'FISHER', 'USA', 2750);
INSERT INTO JOMUMA1.AJEDRECI VALUES(DEFAULT, 'GARRY', 'KASPAROV', 'RUSIA', 2850);
INSERT INTO JOMUMA1.AJEDRECI VALUES(DEFAULT, 'ANATOLY', 'KARPOV', 'RUSIA', 2790);
